name = "CondaPkg"
uuid = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
authors = ["Christopher Doris <github.com/cjdoris>"]
version = "0.2.3"

[deps]
MicroMamba = "0b3b1443-0f03-428d-bdfb-f27f9c1191ea"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
julia = "1"
MicroMamba = "0.1.1"

[targets]
test = ["Test"]