name = "CondaPkg"
uuid = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
authors = ["Christopher Doris <github.com/cjdoris>"]
version = "0.2.21"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MicroMamba = "0b3b1443-0f03-428d-bdfb-f27f9c1191ea"
Pidfile = "fa939f87-e72e-5be4-a000-7fc836dbe307"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
JSON3 = "1.9"
MicroMamba = "0.1.4"
Pidfile = "1.3"
julia = "1"
Preferences = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
