name = "CondaPkg"
uuid = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
authors = ["Christopher Doris <github.com/cjdoris>"]
version = "0.2.9"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MicroMamba = "0b3b1443-0f03-428d-bdfb-f27f9c1191ea"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
MicroMamba = "0.1.4"
JSON3 = "1.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
